// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQanm72Iyiu_kdI3AHE2pD8Y4cCCE9_8',
    appId: '1:597331013532:android:b84404044bddd4347c6259',
    messagingSenderId: '597331013532',
    projectId: 'chatsync-9f109',
    storageBucket: 'chatsync-9f109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8EvMc3jEg_QYsCVej2T6XXF5YctlUMV4',
    appId: '1:597331013532:ios:5af42ca36ed6f73f7c6259',
    messagingSenderId: '597331013532',
    projectId: 'chatsync-9f109',
    storageBucket: 'chatsync-9f109.appspot.com',
    androidClientId: '597331013532-vso56sngnumvdq7dj70fbfm6mekqa2b2.apps.googleusercontent.com',
    iosClientId: '597331013532-r99gs9o9hbg9lumrsgr9gfqcr2alib22.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsync',
  );
}
